name: maven ci/cd pipeline

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
          
    steps:
      - name: Checkout mein Repo
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build und Test
        run: mvn clean test package
      
      - name: Anwendung verpacken mit 7zip
        run: 7z a backend-application.7z target/*

      - name: Deployment
        run: echo "Backend wurde erfolgreich deployed!"