name: Java Maven CI/CD Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean compile

      - name: Test with Maven
        run: mvn test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Simulation
        run: echo "Deployment Simulation"

  artifact:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Anwendung verpacken
        run: 7z a springboot-backend.7z target/*.jar
